In [9]:
import yfinance as yf
import pandas as pd
from pathlib import Path

In [10]:
DATA_DIR = Path("data")

STOCKS = {
    "hdfc": "HDFCBANK.NS",
    "infosys": "INFY.NS",
}

START_DATE = "2015-01-01"
END_DATE = None

In [11]:
for folder in STOCKS:
    (DATA_DIR / folder).mkdir(parents=True, exist_ok=True)

In [12]:
for name, ticker in STOCKS.items():
    print(f"Downloading {ticker}...")

    df = yf.download(
        ticker,
        start=START_DATE,
        end=END_DATE,
        interval="1d",
        auto_adjust=False,
        progress=False,
        multi_level_index=False,
    )

    df = df.reset_index()

    output_path = DATA_DIR / name / f"{ticker.replace('.NS', '')}.csv"
    df.to_csv(output_path, index=False)

    print(f"✓ Saved {len(df):,} rows → {output_path}")

Downloading HDFCBANK.NS...
✓ Saved 2,898 rows → data/hdfc/HDFCBANK.csv
Downloading INFY.NS...
✓ Saved 2,898 rows → data/infosys/INFY.csv

In [13]:
hdfc = pd.read_csv(DATA_DIR / "hdfc" / "HDFCBANK.csv")
infosys = pd.read_csv(DATA_DIR / "infosys" / "INFY.csv")

print("HDFC Bank:")
display(hdfc.head())

print("\nInfosys:")
display(infosys.head())

HDFC Bank:

,Date,Adj Close,Close,High,Low,Open,Volume
0,2015-01-01,213.700867,238.012497,238.600006,236.262497,237.750000,3544940
1,2015-01-02,216.675018,241.324997,242.324997,237.600006,237.600006,5900384
2,2015-01-05,214.845612,239.287506,242.637497,238.774994,242.500000,4796000
3,2015-01-06,211.501114,235.562500,239.137497,234.387497,238.500000,8219680
4,2015-01-07,212.118362,236.250000,237.837494,234.062500,234.925003,5746112

Infosys:

,Date,Adj Close,Close,High,Low,Open,Volume
0,2015-01-01,359.980988,493.600006,495.500000,489.225006,492.237488,2002764
1,2015-01-02,367.055298,503.299988,504.762512,493.000000,493.000000,6778320
2,2015-01-05,363.901062,498.975006,507.500000,494.375000,502.475006,9937024
3,2015-01-06,356.298096,488.549988,496.250000,483.524994,495.000000,9667316
4,2015-01-07,358.002808,490.887512,493.687500,487.500000,491.250000,7249916

In [14]:
print(f"HDFC Bank : {len(hdfc):,} rows")
print(f"Infosys   : {len(infosys):,} rows")

HDFC Bank : 2,898 rows
Infosys   : 2,898 rows

In [15]:
for name, df in [("HDFC Bank", hdfc), ("Infosys", infosys)]:
    df["Date"] = pd.to_datetime(df["Date"])

    print(
        f"{name}: "
        f"{df['Date'].min().date()} → {df['Date'].max().date()}"
    )

HDFC Bank: 2015-01-01 → 2026-09-21
Infosys: 2015-01-01 → 2026-09-21

In [16]:
print("HDFC Bank missing values:")
display(hdfc.isnull().sum())

print("\nInfosys missing values:")
display(infosys.isnull().sum())

HDFC Bank missing values:

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Infosys missing values:

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [17]:
print("HDFC Bank")
display(hdfc.info())

print("\nInfosys")
display(infosys.info())

HDFC Bank
<class 'pandas.DataFrame'>
RangeIndex: 2898 entries, 0 to 2897
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2898 non-null   datetime64[us]
 1   Adj Close  2898 non-null   float64
 2   Close      2898 non-null   float64
 3   High       2898 non-null   float64
 4   Low        2898 non-null   float64
 5   Open       2898 non-null   float64
 6   Volume     2898 non-null   int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 158.6 KB

None

Infosys
<class 'pandas.DataFrame'>
RangeIndex: 2898 entries, 0 to 2897
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2898 non-null   datetime64[us]
 1   Adj Close  2898 non-null   float64
 2   Close      2898 non-null   float64
 3   High       2898 non-null   float64
 4   Low        2898 non-null   float64
 5   Open       2898 non-null   float64
 6   Volume     2898 non-null   int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 158.6 KB

None